# Generated by Django 6.0.5 on 2026-06-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
